---
title: "MW_APP_CMA"
author: "JCLAraujo"
date: "28/05/2020"
output: 
  html_document:
    keep_md: True
    toc: True
---
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Carrega os pacotes 
```{r}
require(raster)
require(rgdal)
require(dplyr)
require(plyr)
```

Aplica MW no raster referente a 2007
```{r, fig.align='center'}
r<-raster("./data_use/raster/RASTER_CMA_07.tif")
r2<-r

r2[r2 < 3] <- 0
r2[r2 > 3] <- 0
r2[r2 == 3] <- 1

m<-matrix(1, nrow=11, ncol=11)
r2.focal<-focal(r2, m, fun=mean)
plot(r2.focal)
plot(r2, add=TRUE, col=c("transparent", "black"))
```

Aplica o MW no raster referente a 2017
```{r, fig.align='center'}
r017<-raster("./data_use/raster/RASTER_CMA_017.tif")

r3<-r017

r3[r3 < 3] <- 0
r3[r3 > 3] <- 0
r3[r3 == 3] <- 1

m<-matrix(1, nrow=11, ncol=11)
r3.focal<-focal(r3, m, fun=mean)
plot(r3.focal)
plot(r3, add=TRUE, col=c("transparent", "black"))

```

Aqui verificamos quantos existe de area florestada (Falta coisa)
```{r, eval=FALSE}
CMA_all<-readOGR(dsn="./data_use",layer="SP_3509452_APP_USO")

ff<-CMA_all@data$CLASSE_USO

ff<-mapvalues(ff, from = c(
  "área antropizada", "área edificada", "silvicultura", 
  "formação florestal", "formação não florestal"), to = c(0,0,0,1,1))
fft<-ff == 1
ab<-disaggregate(CMA_all[fft,])

```

Função para verificar Fragmentos ligados por APP (Falta coisa)
```{r, eval=FALSE}
clip.outside<-function(area2clip, clippingArea){
  
  gI <- gIntersects(area2clip, clippingArea, byid = TRUE )
  clip.out.r <- area2clip[ which(gI) , ]
  return(clip.out.r)
}

APP_Ligadas<-clip.outside(,)
```
